[package]
name = "jira"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.40.0", features = ["concat_str", "lazy", "strings"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
log = "0.4"
env_logger = "0.11.3"
